---
- name: update console
  hosts: all
  vars:
    oh_my_zsh_theme: blake
    oh_my_zsh_plugins:
      - git
      - blake-common
      - cp
      - gradle
      - docker
      - docker-compose
      - tmux
      - zsh-autosuggestions
    oh_my_zsh_install: yes
    usernames: "{{ [ansible_user] + other_users|default([])}}"
  pre_tasks:
    - set_fact:
        username_list: "{{ username_list|default([]) +
                   [{'username': item}] }}"
      loop: "{{ usernames }}"
  roles:
    - role: ansible-role-oh-my-zsh
      users: "{{ username_list }}"
  tasks:
  - name: install packages
    become: yes
    package:
      name:
        - tmux
        - rsync
        - zsh
        - git
      state: present
  - name: set up users
    include_tasks: setup_shell_user.yaml
    loop: "{{ usernames }}"
